module.exports = {
  ROLES: {
    CUSTOMER: 'CUSTOMER',
    STAFF: 'STAFF',
    ADMIN: 'ADMIN'
  },
  ACCOUNT_TYPES: {
    SAVINGS: 'SAVINGS',
    CURRENT: 'CURRENT'
  },
  ACCOUNT_STATUS: {
    PENDING_APPROVAL: 'PENDING_APPROVAL',
    ACTIVE: 'ACTIVE',
    FROZEN: 'FROZEN',
    REJECTED: 'REJECTED',
    CLOSED: 'CLOSED'
  },
  TRANSACTION_TYPES: {
    DEPOSIT: 'DEPOSIT',
    WITHDRAWAL: 'WITHDRAWAL',
    TRANSFER_DEBIT: 'TRANSFER_DEBIT',
    TRANSFER_CREDIT: 'TRANSFER_CREDIT',
    INTEREST: 'INTEREST'
  },
  TRANSACTION_STATUS: {
    COMPLETED: 'COMPLETED',
    PENDING: 'PENDING',
    FAILED: 'FAILED'
  },
  APPROVAL_DECISIONS: {
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    FROZEN: 'FROZEN',
    UNFROZEN: 'UNFROZEN'
  },
  LIMITS: {
    MIN_BALANCE_SAVINGS: Number(process.env.MIN_BALANCE_SAVINGS) || 1000,
    MIN_BALANCE_CURRENT: Number(process.env.MIN_BALANCE_CURRENT) || 5000,
    DAILY_TRANSFER_LIMIT: Number(process.env.DAILY_TRANSFER_LIMIT) || 100000,
    FLAGGED_TRANSACTION_THRESHOLD: Number(process.env.FLAGGED_TRANSACTION_THRESHOLD) || 50000,
    SAVINGS_INTEREST_RATE_ANNUAL: Number(process.env.SAVINGS_INTEREST_RATE_ANNUAL) || 4.0
  }
};
